# Generated by Django 3.2.8 on 2021-10-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonUnite', '0002_remove_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='price_gems',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
