# Generated by Django 3.2.8 on 2021-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonUnite', '0003_pokemon_price_gems'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='attack_type',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='damage_type',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='desc',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='difficulty',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='price_aeos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tier',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
    ]
