# Generated by Django 3.2.8 on 2021-10-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonUnite', '0004_auto_20211017_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='role',
            field=models.CharField(default='defaultValue', max_length=100),
        ),
    ]
